package com.arslan.customanimator.utils

object CommandSuggestions {

    data class Suggestion(val token: String, val description: String)

    private const val PACKAGES = "%packages%"

    private val separators = charArrayOf(';', '|', '&', '\n')

    private val aliases: List<Pair<List<String>, List<String>>> = listOf(
        listOf("cmd", "package") to listOf("pm"),
        listOf("cmd", "activity") to listOf("am")
    )

    private val options: Map<String, List<String>> = mapOf(
        "pm" to listOf(
            "list", "path", "dump", "install", "uninstall", "clear", "enable", "disable",
            "disable-user", "hide", "unhide", "suspend", "unsuspend", "default-state",
            "grant", "revoke", "reset-permissions", "compile", "bg-dexopt-job",
            "trim-caches", "get-app-links", "set-home-activity", "get-install-location"
        ),
        "pm list" to listOf(
            "packages", "permissions", "permission-groups", "features",
            "instrumentation", "libraries", "users", "staged-sessions"
        ),
        "pm list packages" to listOf(
            "-s", "-3", "-d", "-e", "-u", "-f", "-i", "-U", "--user",
            "--show-versioncode", "--apex-only", "--uid"
        ),
        "pm list permissions" to listOf("-g", "-f", "-s", "-u", "-d"),
        "pm install" to listOf("-r", "-t", "-d", "-g", "-i", "--user", "--install-location"),
        "pm uninstall" to listOf("-k", "--user", "--versionCode"),
        "pm clear" to listOf("--user"),
        "pm path" to listOf("--user"),
        "pm enable" to listOf("--user"),
        "pm disable" to listOf("--user"),
        "pm disable-user" to listOf("--user"),
        "pm hide" to listOf("--user"),
        "pm unhide" to listOf("--user"),
        "pm suspend" to listOf("--user"),
        "pm unsuspend" to listOf("--user"),
        "pm grant" to listOf("--user"),
        "pm revoke" to listOf("--user"),
        "pm compile" to listOf("-m", "-r", "-f", "-c", "--reset", "-a", "--secondary-dex"),
        "pm get-app-links" to listOf("--user"),

        "am" to listOf(
            "start", "start-activity", "start-service", "start-foreground-service",
            "stop-service", "broadcast", "force-stop", "stop-app", "kill", "kill-all",
            "crash", "instrument", "set-debug-app", "clear-debug-app", "monitor",
            "hang", "restart", "idle-maintenance", "screen-compat", "get-current-user",
            "switch-user", "send-trim-memory", "trace-ipc", "dumpheap"
        ),
        "am start" to listOf(
            "-n", "-a", "-d", "-t", "-c", "-e", "--es", "--ei", "--ez", "--el", "--ef",
            "--eu", "--user", "-W", "-S", "-D", "-R", "--activity-clear-top",
            "--activity-single-top", "--activity-new-task"
        ),
        "am start-activity" to listOf("-n", "-a", "-d", "-t", "-c", "--user", "-W", "-S"),
        "am start-service" to listOf("-n", "-a", "--user", "--es", "--ei", "--ez"),
        "am start-foreground-service" to listOf("-n", "-a", "--user", "--es", "--ei", "--ez"),
        "am broadcast" to listOf(
            "-a", "-n", "-p", "-d", "-c", "--user", "--es", "--ei", "--ez", "--receiver-foreground"
        ),
        "am force-stop" to listOf("--user"),
        "am stop-app" to listOf("--user"),
        "am kill" to listOf("--user"),
        "am instrument" to listOf("-w", "-r", "-e", "-p", "--user", "--no-window-animation"),
        "am screen-compat" to listOf("on", "off"),
        "am monitor" to listOf("--gdb"),

        "cmd" to listOf(
            "-l", "package", "activity", "appops", "settings", "statusbar", "notification",
            "power", "wifi", "connectivity", "display", "media_session", "jobscheduler",
            "device_config", "shortcut", "role", "uimode", "overlay", "battery",
            "deviceidle", "thermalservice", "input_method", "audio", "location",
            "netpolicy", "user", "window", "alarm", "telecom", "vibrator", "sensorservice"
        ),
        "cmd statusbar" to listOf(
            "expand-notifications", "expand-settings", "collapse", "add-tile", "remove-tile",
            "click-tile", "check-support", "get-status-icons", "send-disable-flag"
        ),
        "cmd power" to listOf(
            "set-mode", "set-adaptive-power-saver-enabled", "set-fixed-performance-mode-enabled"
        ),
        "cmd power set-mode" to listOf("0", "1", "2"),
        "cmd notification" to listOf(
            "list", "post", "allow_listener", "disallow_listener", "allow_assistant"
        ),
        "cmd deviceidle" to listOf(
            "enable", "disable", "step", "force-idle", "unforce", "whitelist",
            "tempwhitelist", "get"
        ),
        "cmd deviceidle get" to listOf("light", "deep", "force", "screen", "charging", "network"),
        "cmd battery" to listOf("set", "unplug", "reset", "suspend_input"),
        "cmd battery set" to listOf(
            "level", "status", "ac", "usb", "wireless", "present", "temp", "counter", "invalid"
        ),
        "cmd overlay" to listOf(
            "list", "enable", "disable", "enable-exclusive", "set-priority", "lookup", "dump"
        ),
        "cmd uimode" to listOf("night", "car"),
        "cmd uimode night" to listOf("yes", "no", "auto", "custom"),
        "cmd uimode car" to listOf("yes", "no"),
        "cmd display" to listOf(
            "set-match-content-frame-rate-pref", "get-match-content-frame-rate-pref",
            "set-brightness", "reset-brightness-configuration"
        ),
        "cmd shortcut" to listOf("reset-throttling", "reset-all-throttling", "clear-shortcuts"),
        "cmd role" to listOf(
            "get-role-holders", "add-role-holder", "remove-role-holder", "clear-role-holders"
        ),
        "cmd jobscheduler" to listOf("run", "timeout", "cancel", "monitor-battery"),
        "cmd wifi" to listOf(
            "status", "set-wifi-enabled", "list-scan-results", "start-scan",
            "list-networks", "forget-network", "set-scan-always-available"
        ),
        "cmd wifi set-wifi-enabled" to listOf("enabled", "disabled"),
        "cmd user" to listOf("list", "create-user", "remove-user", "get-max-users"),
        "cmd alarm" to listOf("set-time", "set-timezone", "get-config-version"),
        "cmd input_method" to listOf("list", "enable", "disable", "set", "reset"),

        "settings" to listOf("--user", "get", "put", "delete", "list", "reset"),
        "settings get" to listOf("global", "system", "secure"),
        "settings put" to listOf("global", "system", "secure"),
        "settings delete" to listOf("global", "system", "secure"),
        "settings list" to listOf("global", "system", "secure"),
        "settings reset" to listOf("global", "secure"),

        "dumpsys" to listOf(
            "-l", "activity", "package", "power", "battery", "batterystats", "window",
            "display", "meminfo", "cpuinfo", "gfxinfo", "input", "notification", "alarm",
            "jobscheduler", "media_session", "audio", "wifi", "connectivity", "netstats",
            "deviceidle", "appops", "usagestats", "sensorservice", "thermalservice",
            "statusbar", "SurfaceFlinger", "telephony.registry", "location", "procstats"
        ),
        "dumpsys activity" to listOf(
            "activities", "services", "providers", "broadcasts", "intents", "processes",
            "recents", "top", "starter", "lru"
        ),
        "dumpsys package" to listOf(
            "packages", "permissions", "permission-groups", "libraries", "features",
            "preferred-xml", "install-sessions"
        ),
        "dumpsys meminfo" to listOf("-a", "-d", "-c", "-s", "--oom"),
        "dumpsys window" to listOf("windows", "displays", "policy", "tokens", "visible-apps"),
        "dumpsys battery" to listOf("set", "unplug", "reset"),
        "dumpsys battery set" to listOf(
            "level", "status", "ac", "usb", "wireless", "present", "temp"
        ),
        "dumpsys deviceidle" to listOf(
            "enable", "disable", "step", "force-idle", "unforce", "whitelist", "get"
        ),
        "dumpsys batterystats" to listOf("--reset", "--checkin", "--charged", "--history"),
        "dumpsys procstats" to listOf("--hours", "--full-details", "--current"),

        "svc" to listOf("power", "wifi", "data", "usb", "nfc", "bluetooth"),
        "svc power" to listOf("stayon", "reboot", "shutdown"),
        "svc power stayon" to listOf("true", "false", "usb", "ac", "wireless"),
        "svc wifi" to listOf("enable", "disable"),
        "svc data" to listOf("enable", "disable"),
        "svc nfc" to listOf("enable", "disable"),
        "svc bluetooth" to listOf("enable", "disable"),
        "svc usb" to listOf("setFunctions", "getFunctions", "setScreenUnlockedFunctions"),

        "wm" to listOf(
            "size", "density", "scaling", "dismiss-keyguard", "user-rotation", "folded-area"
        ),
        "wm size" to listOf("reset", "-d"),
        "wm density" to listOf("reset", "-d"),
        "wm scaling" to listOf("off", "auto"),
        "wm user-rotation" to listOf("free", "lock", "-d"),

        "input" to listOf(
            "text", "keyevent", "tap", "swipe", "draganddrop", "press", "roll",
            "motionevent", "keycombination"
        ),
        "input keyevent" to listOf("--longpress"),

        "ime" to listOf("list", "enable", "disable", "set", "reset"),
        "ime list" to listOf("-a", "-s"),
        "ime enable" to listOf("--user"),
        "ime disable" to listOf("--user"),
        "ime set" to listOf("--user"),

        "appops" to listOf(
            "get", "set", "reset", "list", "start", "stop", "query-op",
            "write-settings", "read-settings"
        ),

        "device_config" to listOf(
            "list", "get", "put", "delete", "reset",
            "set_sync_disabled_for_tests", "get_sync_disabled_for_tests"
        ),

        "logcat" to listOf(
            "-d", "-c", "-v", "-b", "-t", "-s", "-e", "-m", "-f", "-g", "-T",
            "--pid", "*:E", "*:W", "*:I", "*:S"
        ),
        "logcat -b" to listOf("main", "system", "crash", "events", "radio", "all", "default"),
        "logcat -v" to listOf(
            "brief", "long", "process", "raw", "tag", "thread", "threadtime", "time", "color"
        ),

        "service" to listOf("list", "check", "call"),

        "bmgr" to listOf(
            "enabled", "enable", "backupnow", "restore", "list", "transport", "run",
            "wipe", "fullbackup"
        ),
        "bmgr backupnow" to listOf("--all"),
        "bmgr list" to listOf("transports", "sets"),

        "monkey" to listOf(
            "-p", "-v", "-s", "--throttle", "--pct-touch", "--pct-motion",
            "--ignore-crashes", "--ignore-timeouts"
        ),

        "content" to listOf("query", "insert", "update", "delete", "call", "read", "write"),
        "content query" to listOf("--uri", "--user", "--projection", "--where", "--sort"),
        "content insert" to listOf("--uri", "--user", "--bind"),
        "content update" to listOf("--uri", "--user", "--bind", "--where"),
        "content delete" to listOf("--uri", "--user", "--where"),

        "screencap" to listOf("-p", "-d"),
        "screenrecord" to listOf(
            "--size", "--bit-rate", "--time-limit", "--verbose", "--bugreport", "--rotate"
        ),
        "reboot" to listOf("recovery", "bootloader", "-p"),
        "locksettings" to listOf(
            "set-pin", "set-password", "set-pattern", "clear", "verify",
            "get-disabled", "set-disabled", "require-strong-auth"
        ),
        "locksettings clear" to listOf("--old"),
        "locksettings set-pin" to listOf("--old"),
        "locksettings set-password" to listOf("--old"),
        "locksettings set-pattern" to listOf("--old"),

        "sm" to listOf("list-disks", "list-volumes", "has-adoptable", "get-primary-storage-uuid"),
        "dmesg" to listOf("-w", "-T", "-c"),

        "ls" to listOf("-l", "-a", "-la", "-lh", "-R", "-t", "-S", "-d", "-Z"),
        "ps" to listOf("-A", "-e", "-f", "-ef", "-o", "-p", "-u", "-T"),
        "top" to listOf("-n", "-m", "-d", "-b", "-H", "-q", "-s"),
        "df" to listOf("-h", "-k", "-a"),
        "du" to listOf("-h", "-s", "-sh", "-a", "-d"),
        "grep" to listOf("-i", "-v", "-r", "-n", "-E", "-c", "-l", "-w", "-o", "-A", "-B"),
        "find" to listOf(
            "-name", "-iname", "-type", "-maxdepth", "-mindepth", "-size", "-mtime",
            "-delete", "-exec", "-print"
        ),
        "rm" to listOf("-r", "-f", "-rf", "-v", "-d"),
        "cp" to listOf("-r", "-f", "-p", "-a", "-v"),
        "mv" to listOf("-f", "-n", "-v"),
        "mkdir" to listOf("-p", "-m"),
        "chmod" to listOf("-R", "644", "755", "777", "+x", "-x"),
        "chown" to listOf("-R"),
        "kill" to listOf("-9", "-15", "-l"),
        "killall" to listOf("-9", "-l", "-v"),
        "mount" to listOf("-o", "-t", "-r", "-w", "remount"),
        "ping" to listOf("-c", "-i", "-s", "-w", "-W"),
        "ip" to listOf("-4", "-6", "addr", "route", "link", "rule", "neigh"),
        "ip addr" to listOf("show", "add", "del", "flush"),
        "ip route" to listOf("show", "add", "del", "get", "flush"),
        "ip link" to listOf("show", "set"),
        "head" to listOf("-n", "-c"),
        "tail" to listOf("-n", "-c", "-f"),
        "wc" to listOf("-l", "-w", "-c"),
        "sort" to listOf("-r", "-n", "-u", "-k", "-f"),
        "uniq" to listOf("-c", "-d", "-u", "-i"),
        "cut" to listOf("-d", "-f", "-c"),
        "sed" to listOf("-n", "-e", "-i", "-E"),
        "tar" to listOf("-c", "-x", "-t", "-z", "-v", "-f", "-czf", "-xzf"),
        "unzip" to listOf("-l", "-o", "-d", "-q"),
        "xargs" to listOf("-n", "-I", "-0"),
        "stat" to listOf("-c", "-f", "-L"),
        "setenforce" to listOf("0", "1", "Enforcing", "Permissive"),
        "date" to listOf("-u", "-s", "+%Y-%m-%d", "+%H:%M:%S", "+%s"),
        "free" to listOf("-h", "-m", "-b"),
        "netstat" to listOf("-a", "-n", "-t", "-u", "-l", "-p"),
        "getevent" to listOf("-l", "-t", "-p", "-i")
    )

    private val args: Map<String, List<List<String>>> = mapOf(
        "pm path" to listOf(listOf(PACKAGES)),
        "pm dump" to listOf(listOf(PACKAGES)),
        "pm clear" to listOf(listOf(PACKAGES)),
        "pm uninstall" to listOf(listOf(PACKAGES)),
        "pm enable" to listOf(listOf(PACKAGES)),
        "pm disable" to listOf(listOf(PACKAGES)),
        "pm disable-user" to listOf(listOf(PACKAGES)),
        "pm hide" to listOf(listOf(PACKAGES)),
        "pm unhide" to listOf(listOf(PACKAGES)),
        "pm suspend" to listOf(listOf(PACKAGES)),
        "pm unsuspend" to listOf(listOf(PACKAGES)),
        "pm default-state" to listOf(listOf(PACKAGES)),
        "pm reset-permissions" to listOf(listOf(PACKAGES)),
        "pm get-app-links" to listOf(listOf(PACKAGES)),
        "pm compile" to listOf(listOf(PACKAGES)),
        "pm grant" to listOf(listOf(PACKAGES), runtimePermissions()),
        "pm revoke" to listOf(listOf(PACKAGES), runtimePermissions()),
        "pm trim-caches" to listOf(listOf("128M", "256M", "512M", "1G", "2G")),
        "pm compile -m" to listOf(listOf("verify", "speed-profile", "speed", "everything")),
        "pm compile -r" to listOf(
            listOf("first-boot", "boot-after-ota", "install", "bg-dexopt", "cmdline")
        ),
        "pm list packages --user" to listOf(listOf("0")),
        "pm install --install-location" to listOf(listOf("0", "1", "2")),

        "am force-stop" to listOf(listOf(PACKAGES)),
        "am stop-app" to listOf(listOf(PACKAGES)),
        "am kill" to listOf(listOf(PACKAGES)),
        "am crash" to listOf(listOf(PACKAGES)),
        "am start -n" to listOf(listOf(PACKAGES)),
        "am start -a" to listOf(intentActions()),
        "am broadcast -a" to listOf(intentActions()),
        "am broadcast -p" to listOf(listOf(PACKAGES)),
        "am switch-user" to listOf(listOf("0")),
        "am send-trim-memory" to listOf(
            listOf(PACKAGES),
            listOf("HIDDEN", "RUNNING_MODERATE", "BACKGROUND", "RUNNING_LOW", "MODERATE",
                "RUNNING_CRITICAL", "COMPLETE")
        ),
        "am set-debug-app" to listOf(listOf(PACKAGES)),

        "settings get global" to listOf(globalKeys()),
        "settings delete global" to listOf(globalKeys()),
        "settings put global" to listOf(globalKeys()),
        "settings get secure" to listOf(secureKeys()),
        "settings delete secure" to listOf(secureKeys()),
        "settings put secure" to listOf(secureKeys()),
        "settings get system" to listOf(systemKeys()),
        "settings delete system" to listOf(systemKeys()),
        "settings put system" to listOf(systemKeys()),
        "settings reset global" to listOf(
            listOf("untrusted_defaults", "untrusted_clear", "trusted_defaults")
        ),
        "settings reset secure" to listOf(
            listOf("untrusted_defaults", "untrusted_clear", "trusted_defaults")
        ),
        "settings put global window_animation_scale" to listOf(animationScales()),
        "settings put global transition_animation_scale" to listOf(animationScales()),
        "settings put global animator_duration_scale" to listOf(animationScales()),
        "settings put global airplane_mode_on" to listOf(boolInts()),
        "settings put global adb_enabled" to listOf(boolInts()),
        "settings put global development_settings_enabled" to listOf(boolInts()),
        "settings put global stay_on_while_plugged_in" to listOf(listOf("0", "1", "2", "3", "7")),
        "settings put global auto_time" to listOf(boolInts()),
        "settings put global auto_time_zone" to listOf(boolInts()),
        "settings put global heads_up_notifications_enabled" to listOf(boolInts()),
        "settings put system accelerometer_rotation" to listOf(boolInts()),
        "settings put system haptic_feedback_enabled" to listOf(boolInts()),
        "settings put system sound_effects_enabled" to listOf(boolInts()),
        "settings put system vibrate_when_ringing" to listOf(boolInts()),
        "settings put system screen_brightness_mode" to listOf(listOf("0", "1")),
        "settings put system screen_off_timeout" to listOf(
            listOf("15000", "30000", "60000", "120000", "600000", "1800000")
        ),
        "settings put secure ui_night_mode" to listOf(listOf("1", "2")),
        "settings put secure doze_always_on" to listOf(boolInts()),
        "settings put secure navigation_mode" to listOf(listOf("0", "1", "2")),

        "dumpsys package" to listOf(listOf(PACKAGES)),
        "dumpsys gfxinfo" to listOf(listOf(PACKAGES)),
        "dumpsys meminfo" to listOf(listOf(PACKAGES)),
        "dumpsys procstats" to listOf(listOf(PACKAGES)),
        "dumpsys battery set" to listOf(
            listOf("level", "status", "ac", "usb", "wireless", "present", "temp")
        ),
        "cmd battery set" to listOf(
            listOf("level", "status", "ac", "usb", "wireless", "present", "temp")
        ),
        "cmd deviceidle whitelist" to listOf(listOf(PACKAGES)),
        "dumpsys deviceidle whitelist" to listOf(listOf(PACKAGES)),
        "cmd overlay enable" to listOf(listOf(PACKAGES)),
        "cmd overlay disable" to listOf(listOf(PACKAGES)),
        "cmd shortcut clear-shortcuts" to listOf(listOf(PACKAGES)),

        "appops get" to listOf(listOf(PACKAGES), appOps()),
        "appops set" to listOf(listOf(PACKAGES), appOps(), appOpModes()),
        "appops reset" to listOf(listOf(PACKAGES)),
        "appops query-op" to listOf(appOps(), appOpModes()),

        "device_config list" to listOf(deviceConfigNamespaces()),
        "device_config get" to listOf(deviceConfigNamespaces()),
        "device_config put" to listOf(deviceConfigNamespaces()),
        "device_config delete" to listOf(deviceConfigNamespaces()),
        "device_config reset" to listOf(
            listOf("untrusted_defaults", "untrusted_clear", "trusted_defaults"),
            deviceConfigNamespaces()
        ),

        "monkey -p" to listOf(listOf(PACKAGES)),
        "bmgr backupnow" to listOf(listOf(PACKAGES)),
        "am instrument -w" to listOf(listOf(PACKAGES)),

        "svc power reboot" to listOf(listOf("recovery", "bootloader")),
        "wm size" to listOf(listOf("1080x2400", "1440x3200", "720x1600")),
        "wm density" to listOf(listOf("320", "420", "480", "560", "640")),
        "wm user-rotation lock" to listOf(listOf("0", "1", "2", "3")),
        "input keyevent" to listOf(keyEvents()),
        "input text" to listOf(emptyList()),

        "getprop" to listOf(readableProps()),
        "setprop" to listOf(writableProps()),
        "setprop debug.hwui.renderer" to listOf(listOf("skiagl", "skiavk")),
        "setprop debug.hwui.overdraw" to listOf(listOf("show", "false")),
        "setprop persist.sys.usb.config" to listOf(listOf("mtp", "ptp", "none")),

        "service check" to listOf(serviceNames()),
        "service call" to listOf(serviceNames()),
        "pidof" to listOf(listOf(PACKAGES)),
        "killall" to listOf(listOf(PACKAGES)),
        "cat" to listOf(
            listOf(
                "/proc/cpuinfo", "/proc/meminfo", "/proc/version", "/proc/uptime",
                "/proc/stat", "/sys/class/power_supply/battery/capacity",
                "/sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq"
            )
        ),
        "sleep" to listOf(listOf("1", "3", "5", "10")),
        "setenforce" to listOf(listOf("0", "1")),
        "logcat -b" to listOf(
            listOf("main", "system", "crash", "events", "radio", "all", "default")
        ),
        "logcat -v" to listOf(
            listOf("brief", "long", "process", "raw", "tag", "thread", "threadtime", "time", "color")
        ),
        "logcat -t" to listOf(listOf("50", "100", "500", "1000")),
        "screenrecord --size" to listOf(listOf("720x1280", "1080x1920")),
        "screenrecord --time-limit" to listOf(listOf("30", "60", "120", "180")),
        "screenrecord --bit-rate" to listOf(listOf("4000000", "8000000", "16000000"))
    )

    private val topLevel: List<String> = listOf(
        "pm", "am", "cmd", "settings", "dumpsys", "getprop", "setprop", "svc", "wm",
        "input", "ime", "content", "appops", "device_config", "logcat", "service",
        "bmgr", "monkey", "screencap", "screenrecord", "reboot", "locksettings", "sm",
        "bugreport", "dmesg", "getevent", "ls", "cat", "ps", "top", "df", "du", "grep",
        "find", "rm", "cp", "mv", "mkdir", "rmdir", "chmod", "chown", "kill", "killall",
        "mount", "umount", "ping", "ip", "ifconfig", "netstat", "head", "tail", "wc",
        "sort", "uniq", "cut", "sed", "awk", "echo", "touch", "sleep", "date", "uptime",
        "whoami", "id", "getenforce", "setenforce", "pidof", "free", "sync", "stop",
        "start", "printenv", "which", "sh", "toybox", "tar", "unzip", "stat", "md5sum",
        "xargs", "basename", "dirname", "ln", "mkfifo", "wm"
    ).distinct().sorted()

    private val baseDescriptions: Map<String, String> = mapOf(
        "pm" to "Package manager",
        "am" to "Activity manager",
        "cmd" to "Call a system service directly",
        "settings" to "Read and write system settings",
        "dumpsys" to "Dump system service state",
        "getprop" to "Read system properties",
        "setprop" to "Write a system property",
        "svc" to "Toggle power, wifi, data, usb, nfc",
        "wm" to "Window manager: size, density, rotation",
        "input" to "Inject taps, swipes, keys and text",
        "ime" to "Manage input methods",
        "content" to "Query content providers",
        "appops" to "Read and set app operation modes",
        "device_config" to "Read and write feature flags",
        "logcat" to "Read the system log",
        "service" to "List and call binder services",
        "bmgr" to "Backup manager",
        "monkey" to "Send pseudo-random UI events",
        "screencap" to "Take a screenshot to a file",
        "screenrecord" to "Record the screen to a file",
        "reboot" to "Restart the device",
        "locksettings" to "Manage the lock screen credential",
        "sm" to "Storage manager",
        "bugreport" to "Generate a bug report",
        "dmesg" to "Kernel log",
        "getevent" to "Raw input events",
        "ls" to "List directory contents",
        "cat" to "Print a file",
        "ps" to "List running processes",
        "top" to "Live process and CPU usage",
        "df" to "Free space per filesystem",
        "du" to "Disk usage of files and folders",
        "grep" to "Filter lines by pattern",
        "find" to "Search for files",
        "rm" to "Delete files",
        "cp" to "Copy files",
        "mv" to "Move or rename files",
        "mkdir" to "Create a directory",
        "rmdir" to "Remove an empty directory",
        "chmod" to "Change file permissions",
        "chown" to "Change file owner",
        "kill" to "Send a signal to a pid",
        "killall" to "Kill processes by name",
        "mount" to "Mount or remount a filesystem",
        "umount" to "Unmount a filesystem",
        "ping" to "Test network reachability",
        "ip" to "Network addresses and routes",
        "ifconfig" to "Network interfaces",
        "netstat" to "Network connections",
        "head" to "First lines of a file",
        "tail" to "Last lines of a file",
        "wc" to "Count lines, words and bytes",
        "sort" to "Sort lines",
        "uniq" to "Collapse repeated lines",
        "cut" to "Extract columns from lines",
        "sed" to "Stream editor",
        "awk" to "Text processing language",
        "echo" to "Print text",
        "touch" to "Create a file or update its timestamp",
        "sleep" to "Wait for seconds",
        "date" to "Show or set the time",
        "uptime" to "How long the device has been up",
        "whoami" to "Current shell user",
        "id" to "Current uid, gid and groups",
        "getenforce" to "SELinux enforcing state",
        "setenforce" to "Set SELinux enforcing or permissive",
        "pidof" to "Pid of a process by name",
        "free" to "Memory usage",
        "sync" to "Flush pending writes to storage",
        "stop" to "Stop the Android runtime",
        "start" to "Start the Android runtime",
        "printenv" to "Print environment variables",
        "which" to "Locate an executable",
        "sh" to "Run a shell",
        "toybox" to "List built-in toybox applets",
        "tar" to "Create or extract an archive",
        "unzip" to "Extract a zip archive",
        "stat" to "File metadata",
        "md5sum" to "MD5 checksum of a file",
        "xargs" to "Build commands from input",
        "basename" to "Strip the directory from a path",
        "dirname" to "Directory part of a path",
        "ln" to "Create a link",
        "mkfifo" to "Create a named pipe",

        "pm list" to "List packages, permissions, users",
        "pm list packages" to "List installed packages",
        "pm path" to "APK path of a package",
        "pm dump" to "Dump everything about a package",
        "pm install" to "Install an APK from a device path",
        "pm uninstall" to "Uninstall a package",
        "pm clear" to "Delete a package's data and caches",
        "pm enable" to "Enable a package or component",
        "pm disable" to "Disable a package (needs system rights)",
        "pm disable-user" to "Disable a package for this user",
        "pm hide" to "Hide a package",
        "pm unhide" to "Unhide a package",
        "pm suspend" to "Suspend a package",
        "pm unsuspend" to "Unsuspend a package",
        "pm default-state" to "Reset a package to its default state",
        "pm grant" to "Grant a runtime permission",
        "pm revoke" to "Revoke a runtime permission",
        "pm reset-permissions" to "Reset all runtime permissions",
        "pm compile" to "Recompile a package's dex code",
        "pm bg-dexopt-job" to "Run the background dexopt job now",
        "pm trim-caches" to "Free caches until this much space is free",
        "pm get-app-links" to "Show verified app link domains",
        "pm list packages -s" to "System packages only",
        "pm list packages -3" to "Third-party packages only",
        "pm list packages -d" to "Disabled packages only",
        "pm list packages -e" to "Enabled packages only",
        "pm list packages -f" to "Show the APK file path",
        "pm list packages -i" to "Show the installer package",
        "pm list packages -u" to "Include uninstalled packages",
        "pm install -r" to "Reinstall, keeping data",
        "pm install -d" to "Allow a version downgrade",
        "pm install -g" to "Grant all permissions",
        "pm install -t" to "Allow test APKs",
        "pm uninstall -k" to "Keep data and cache directories",
        "pm compile -m" to "Compilation filter",
        "pm compile -r" to "Compilation reason",
        "pm compile -f" to "Force recompilation",
        "pm compile -a" to "All packages",

        "am start" to "Start an activity",
        "am start-activity" to "Start an activity",
        "am start-service" to "Start a service",
        "am start-foreground-service" to "Start a foreground service",
        "am stop-service" to "Stop a service",
        "am broadcast" to "Send a broadcast intent",
        "am force-stop" to "Force stop a package",
        "am stop-app" to "Stop an app without resetting its state",
        "am kill" to "Kill background processes of a package",
        "am kill-all" to "Kill all background processes",
        "am crash" to "Force a crash in a package",
        "am instrument" to "Run an instrumentation test",
        "am monitor" to "Watch for crashes and ANRs",
        "am get-current-user" to "Current user id",
        "am switch-user" to "Switch to another user",
        "am send-trim-memory" to "Ask a process to release memory",
        "am idle-maintenance" to "Trigger idle maintenance now",
        "am start -n" to "Component: package/.Activity",
        "am start -a" to "Intent action",
        "am start -d" to "Intent data URI",
        "am start -W" to "Wait for the launch to finish",
        "am broadcast -a" to "Intent action",
        "am broadcast -p" to "Target package",

        "settings get" to "Read a setting",
        "settings put" to "Write a setting",
        "settings delete" to "Remove a setting",
        "settings list" to "List every setting in a namespace",
        "settings reset" to "Reset settings changed by apps",
        "settings get global" to "Device-wide namespace",
        "settings put global" to "Device-wide namespace",
        "settings get secure" to "Read-only-to-apps namespace",
        "settings put secure" to "Read-only-to-apps namespace",
        "settings get system" to "User preference namespace",
        "settings put system" to "User preference namespace",
        "settings put global window_animation_scale" to "Window open and close animation speed",
        "settings put global transition_animation_scale" to "Activity transition animation speed",
        "settings put global animator_duration_scale" to "In-app animator speed",

        "svc power" to "Screen stay-on, reboot, shutdown",
        "svc power stayon" to "Keep the screen on while charging",
        "svc wifi" to "Turn Wi-Fi on or off",
        "svc data" to "Turn mobile data on or off",
        "svc usb" to "USB functions",
        "wm size" to "Get or set the resolution",
        "wm density" to "Get or set the DPI",
        "wm scaling" to "Force GPU scaling off or auto",
        "wm dismiss-keyguard" to "Unlock the screen",
        "wm user-rotation" to "Lock or free the screen rotation",
        "input text" to "Type a string into the focused field",
        "input keyevent" to "Send a key",
        "input tap" to "Tap at x y",
        "input swipe" to "Swipe from x1 y1 to x2 y2",

        "cmd -l" to "List every available service",
        "cmd statusbar" to "Expand or collapse the status bar",
        "cmd deviceidle" to "Doze state and battery whitelist",
        "cmd battery" to "Fake the battery state",
        "cmd battery reset" to "Restore the real battery state",
        "cmd overlay" to "Manage runtime resource overlays",
        "cmd uimode night" to "Force dark or light mode",
        "cmd power set-mode" to "0 none, 1 low power, 2 performance",

        "dumpsys -l" to "List every dumpable service",
        "dumpsys battery" to "Battery state",
        "dumpsys battery reset" to "Restore the real battery state",
        "dumpsys meminfo" to "Memory per process",
        "dumpsys gfxinfo" to "Frame rendering timings",
        "dumpsys cpuinfo" to "CPU usage per process",
        "dumpsys activity" to "Activity manager state",
        "dumpsys window" to "Window manager state",
        "dumpsys package" to "Package manager state",
        "dumpsys batterystats" to "Historical battery usage",

        "appops get" to "Read a package's app op modes",
        "appops set" to "Set an app op mode",
        "appops reset" to "Reset a package's app ops",
        "device_config put" to "Write a flag: namespace key value",
        "logcat -d" to "Dump the log and exit",
        "logcat -c" to "Clear the log buffers",
        "logcat -b" to "Choose a log buffer",
        "logcat -v" to "Output format",
        "logcat -t" to "Print only the last N lines",
        "service list" to "List all binder services",
        "bmgr backupnow" to "Back up now",
        "monkey -p" to "Restrict events to a package",

        "pm set-home-activity" to "Set the default launcher",
        "pm get-install-location" to "Show the default install location",
        "pm list permissions" to "List permissions",
        "pm list permission-groups" to "List permission groups",
        "pm list features" to "List hardware and software features",
        "pm list instrumentation" to "List instrumentation targets",
        "pm list libraries" to "List shared libraries",
        "pm list users" to "List device users",
        "pm list staged-sessions" to "List staged install sessions",
        "pm list packages -U" to "Show the package uid",
        "pm list packages --user" to "Target user id, 0 is the owner",
        "pm list packages --show-versioncode" to "Show version codes",
        "pm list packages --apex-only" to "APEX modules only",
        "pm list packages --uid" to "Packages owned by a uid",
        "pm list permissions -g" to "Group by permission group",
        "pm list permissions -f" to "Show all information",
        "pm list permissions -s" to "Short summary",
        "pm list permissions -u" to "Only permissions users see",
        "pm list permissions -d" to "Dangerous permissions only",
        "pm install -i" to "Set the installer package name",
        "pm install --user" to "Target user id, 0 is the owner",
        "pm install --install-location" to "Where to install: 0 auto, 1 internal, 2 external",
        "pm uninstall --user" to "Target user id, 0 is the owner",
        "pm uninstall --versionCode" to "Only if this version code matches",
        "pm clear --user" to "Target user id, 0 is the owner",
        "pm path --user" to "Target user id, 0 is the owner",
        "pm enable --user" to "Target user id, 0 is the owner",
        "pm disable --user" to "Target user id, 0 is the owner",
        "pm disable-user --user" to "Target user id, 0 is the owner",
        "pm hide --user" to "Target user id, 0 is the owner",
        "pm unhide --user" to "Target user id, 0 is the owner",
        "pm suspend --user" to "Target user id, 0 is the owner",
        "pm unsuspend --user" to "Target user id, 0 is the owner",
        "pm grant --user" to "Target user id, 0 is the owner",
        "pm revoke --user" to "Target user id, 0 is the owner",
        "pm compile -c" to "Extra compile option",
        "pm compile --reset" to "Reset to the default compiled state",
        "pm compile --secondary-dex" to "Compile secondary dex files too",
        "pm get-app-links --user" to "Target user id, 0 is the owner",
        "am set-debug-app" to "Mark a package as the debug target",
        "am clear-debug-app" to "Clear the debug app",
        "am hang" to "Hang the system process (test only)",
        "am restart" to "Restart the system",
        "am screen-compat" to "Screen compatibility mode for a package",
        "am trace-ipc" to "Record binder IPC traces",
        "am dumpheap" to "Dump a process heap to a file",
        "am start -t" to "MIME type",
        "am start -c" to "Intent category",
        "am start -e" to "String extra",
        "am start --es" to "String extra",
        "am start --ei" to "Integer extra",
        "am start --ez" to "Boolean extra",
        "am start --el" to "Long extra",
        "am start --ef" to "Float extra",
        "am start --eu" to "URI extra",
        "am start --user" to "Target user id, 0 is the owner",
        "am start -S" to "Force stop the target before starting",
        "am start -D" to "Wait for a debugger",
        "am start -R" to "Repeat the launch",
        "am start --activity-clear-top" to "Clear activities above the target",
        "am start --activity-single-top" to "Reuse the top activity",
        "am start --activity-new-task" to "Start in a new task",
        "am start-activity -n" to "Component: package/.Class",
        "am start-activity -a" to "Intent action",
        "am start-activity -d" to "Intent data URI",
        "am start-activity -t" to "MIME type",
        "am start-activity -c" to "Intent category",
        "am start-activity --user" to "Target user id, 0 is the owner",
        "am start-activity -W" to "Wait for the launch to finish",
        "am start-activity -S" to "Force stop the target before starting",
        "am start-service -n" to "Component: package/.Class",
        "am start-service -a" to "Intent action",
        "am start-service --user" to "Target user id, 0 is the owner",
        "am start-service --es" to "String extra",
        "am start-service --ei" to "Integer extra",
        "am start-service --ez" to "Boolean extra",
        "am start-foreground-service -n" to "Component: package/.Class",
        "am start-foreground-service -a" to "Intent action",
        "am start-foreground-service --user" to "Target user id, 0 is the owner",
        "am start-foreground-service --es" to "String extra",
        "am start-foreground-service --ei" to "Integer extra",
        "am start-foreground-service --ez" to "Boolean extra",
        "am broadcast -n" to "Component: package/.Class",
        "am broadcast -d" to "Intent data URI",
        "am broadcast -c" to "Intent category",
        "am broadcast --user" to "Target user id, 0 is the owner",
        "am broadcast --es" to "String extra",
        "am broadcast --ei" to "Integer extra",
        "am broadcast --ez" to "Boolean extra",
        "am broadcast --receiver-foreground" to "Deliver as a foreground broadcast",
        "am force-stop --user" to "Target user id, 0 is the owner",
        "am stop-app --user" to "Target user id, 0 is the owner",
        "am kill --user" to "Target user id, 0 is the owner",
        "am instrument -w" to "Wait until the run finishes",
        "am instrument -r" to "Raw output",
        "am instrument -e" to "Test argument key and value",
        "am instrument -p" to "Write profiling data to a file",
        "am instrument --user" to "Target user id, 0 is the owner",
        "am instrument --no-window-animation" to "Disable animations during the run",
        "am screen-compat on" to "Enable compatibility mode",
        "am screen-compat off" to "Disable compatibility mode",
        "am monitor --gdb" to "Wait for gdb when something crashes",
        "cmd package" to "Package manager service, same as pm",
        "cmd activity" to "Activity manager service, same as am",
        "cmd appops" to "App operations service",
        "cmd settings" to "Settings service",
        "cmd notification" to "Notification service",
        "cmd power" to "Power service",
        "cmd wifi" to "Wi-Fi service",
        "cmd connectivity" to "Connectivity service",
        "cmd display" to "Display service",
        "cmd media_session" to "Media session service",
        "cmd jobscheduler" to "Job scheduler service",
        "cmd device_config" to "Feature flag service",
        "cmd shortcut" to "App shortcut service",
        "cmd role" to "Default app role service",
        "cmd uimode" to "Night and car mode service",
        "cmd thermalservice" to "Thermal service",
        "cmd input_method" to "Input method service",
        "cmd audio" to "Audio service",
        "cmd location" to "Location service",
        "cmd netpolicy" to "Network policy service",
        "cmd user" to "User manager service",
        "cmd window" to "Window manager service",
        "cmd alarm" to "Alarm service",
        "cmd telecom" to "Telecom service",
        "cmd vibrator" to "Vibrator service",
        "cmd sensorservice" to "Sensor service",
        "cmd statusbar expand-notifications" to "Open the notification shade",
        "cmd statusbar expand-settings" to "Open Quick Settings",
        "cmd statusbar collapse" to "Close the shade",
        "cmd statusbar add-tile" to "Add a Quick Settings tile",
        "cmd statusbar remove-tile" to "Remove a Quick Settings tile",
        "cmd statusbar click-tile" to "Click a Quick Settings tile",
        "cmd statusbar check-support" to "Check tile API support",
        "cmd statusbar get-status-icons" to "List status bar icons",
        "cmd statusbar send-disable-flag" to "Disable parts of the status bar",
        "cmd power set-adaptive-power-saver-enabled" to "Adaptive battery saver on or off",
        "cmd power set-fixed-performance-mode-enabled" to "Fixed performance mode on or off",
        "cmd power set-mode 0" to "Power mode value passed to the service",
        "cmd power set-mode 1" to "Power mode value passed to the service",
        "cmd power set-mode 2" to "Power mode value passed to the service",
        "cmd notification list" to "List posted notifications",
        "cmd notification post" to "Post a test notification",
        "cmd notification allow_listener" to "Allow a notification listener",
        "cmd notification disallow_listener" to "Block a notification listener",
        "cmd notification allow_assistant" to "Allow a notification assistant",
        "cmd deviceidle enable" to "Turn Doze on",
        "cmd deviceidle disable" to "Turn Doze off",
        "cmd deviceidle step" to "Advance to the next Doze state",
        "cmd deviceidle force-idle" to "Force Doze now",
        "cmd deviceidle unforce" to "Leave forced Doze",
        "cmd deviceidle whitelist" to "Battery optimization exceptions",
        "cmd deviceidle tempwhitelist" to "Temporary exception for a package",
        "cmd deviceidle get" to "Read a Doze value",
        "cmd deviceidle get light" to "Light Doze state",
        "cmd deviceidle get deep" to "Deep Doze state",
        "cmd deviceidle get force" to "Forced idle state",
        "cmd deviceidle get screen" to "Screen state used by Doze",
        "cmd deviceidle get charging" to "Charging state used by Doze",
        "cmd deviceidle get network" to "Network state used by Doze",
        "cmd battery set" to "Fake a battery value",
        "cmd battery unplug" to "Pretend the charger is unplugged",
        "cmd battery suspend_input" to "Ignore the real battery input",
        "cmd battery set level" to "Battery percentage",
        "cmd battery set status" to "Charging status code",
        "cmd battery set ac" to "AC charger connected, 0 or 1",
        "cmd battery set usb" to "USB charger connected, 0 or 1",
        "cmd battery set wireless" to "Wireless charger connected, 0 or 1",
        "cmd battery set present" to "Battery present, 0 or 1",
        "cmd battery set temp" to "Battery temperature in tenths of a degree",
        "cmd battery set counter" to "Charge counter",
        "cmd battery set invalid" to "Mark the value as invalid",
        "cmd overlay list" to "List overlays",
        "cmd overlay enable" to "Enable an overlay",
        "cmd overlay disable" to "Disable an overlay",
        "cmd overlay enable-exclusive" to "Enable one overlay and disable the rest",
        "cmd overlay set-priority" to "Change overlay priority",
        "cmd overlay lookup" to "Look up an overlay resource value",
        "cmd overlay dump" to "Dump overlay state",
        "cmd uimode car" to "Car mode on or off",
        "cmd uimode night yes" to "Always dark",
        "cmd uimode night no" to "Always light",
        "cmd uimode night auto" to "Follow sunrise and sunset",
        "cmd uimode night custom" to "Follow a custom schedule",
        "cmd uimode car yes" to "Turn car mode on",
        "cmd uimode car no" to "Turn car mode off",
        "cmd display set-match-content-frame-rate-pref" to "Frame rate matching preference",
        "cmd display get-match-content-frame-rate-pref" to "Read the frame rate preference",
        "cmd display set-brightness" to "Set brightness from 0 to 1",
        "cmd display reset-brightness-configuration" to "Reset the brightness curve",
        "cmd shortcut reset-throttling" to "Reset shortcut rate limits",
        "cmd shortcut reset-all-throttling" to "Reset rate limits for every app",
        "cmd shortcut clear-shortcuts" to "Delete an app's shortcuts",
        "cmd role get-role-holders" to "Who holds a role",
        "cmd role add-role-holder" to "Give a role to an app",
        "cmd role remove-role-holder" to "Take a role from an app",
        "cmd role clear-role-holders" to "Clear a role",
        "cmd jobscheduler run" to "Run a job now",
        "cmd jobscheduler timeout" to "Time out a running job",
        "cmd jobscheduler cancel" to "Cancel a job",
        "cmd jobscheduler monitor-battery" to "Watch the battery for job decisions",
        "cmd wifi status" to "Wi-Fi state and connection",
        "cmd wifi set-wifi-enabled" to "Turn Wi-Fi on or off",
        "cmd wifi list-scan-results" to "Results of the last scan",
        "cmd wifi start-scan" to "Start a Wi-Fi scan",
        "cmd wifi list-networks" to "Saved networks",
        "cmd wifi forget-network" to "Delete a saved network",
        "cmd wifi set-scan-always-available" to "Scanning while Wi-Fi is off",
        "cmd wifi set-wifi-enabled enabled" to "Turn Wi-Fi on",
        "cmd wifi set-wifi-enabled disabled" to "Turn Wi-Fi off",
        "cmd user list" to "List users",
        "cmd user create-user" to "Create a user",
        "cmd user remove-user" to "Delete a user",
        "cmd user get-max-users" to "Maximum number of users",
        "cmd alarm set-time" to "Set the system time in milliseconds",
        "cmd alarm set-timezone" to "Set the time zone",
        "cmd alarm get-config-version" to "Alarm config version",
        "cmd input_method list" to "List input methods",
        "cmd input_method enable" to "Enable an input method",
        "cmd input_method disable" to "Disable an input method",
        "cmd input_method set" to "Pick the active input method",
        "cmd input_method reset" to "Reset to the default input method",
        "settings --user" to "Target user id, 0 is the owner",
        "settings delete global" to "Device-wide namespace",
        "settings delete system" to "User preference namespace",
        "settings delete secure" to "Read-only-to-apps namespace",
        "settings list global" to "Device-wide namespace",
        "settings list system" to "User preference namespace",
        "settings list secure" to "Read-only-to-apps namespace",
        "settings reset global" to "Device-wide namespace",
        "settings reset secure" to "Read-only-to-apps namespace",
        "dumpsys power" to "Power and wake lock state",
        "dumpsys display" to "Display state",
        "dumpsys input" to "Input devices and state",
        "dumpsys notification" to "Notification state",
        "dumpsys alarm" to "Scheduled alarms",
        "dumpsys jobscheduler" to "Scheduled jobs",
        "dumpsys media_session" to "Media sessions",
        "dumpsys audio" to "Audio state",
        "dumpsys wifi" to "Wi-Fi state",
        "dumpsys connectivity" to "Network connections",
        "dumpsys netstats" to "Network usage statistics",
        "dumpsys deviceidle" to "Doze state",
        "dumpsys appops" to "App operation state",
        "dumpsys usagestats" to "App usage statistics",
        "dumpsys sensorservice" to "Sensor state",
        "dumpsys thermalservice" to "Thermal state",
        "dumpsys statusbar" to "Status bar state",
        "dumpsys SurfaceFlinger" to "Display composition state",
        "dumpsys telephony.registry" to "Telephony state",
        "dumpsys location" to "Location state",
        "dumpsys procstats" to "Process memory statistics",
        "dumpsys activity activities" to "Activity stacks",
        "dumpsys activity services" to "Running services",
        "dumpsys activity providers" to "Content providers",
        "dumpsys activity broadcasts" to "Broadcast queues",
        "dumpsys activity intents" to "Pending intents",
        "dumpsys activity processes" to "Running processes",
        "dumpsys activity recents" to "Recent tasks",
        "dumpsys activity top" to "Foreground activity",
        "dumpsys activity starter" to "Recent activity starts",
        "dumpsys activity lru" to "Process LRU order",
        "dumpsys package packages" to "All package records",
        "dumpsys package permissions" to "Declared permissions",
        "dumpsys package permission-groups" to "Permission groups",
        "dumpsys package libraries" to "Shared libraries",
        "dumpsys package features" to "Device features",
        "dumpsys package preferred-xml" to "Preferred activity settings",
        "dumpsys package install-sessions" to "Open install sessions",
        "dumpsys meminfo -a" to "Everything",
        "dumpsys meminfo -d" to "Dalvik details",
        "dumpsys meminfo -c" to "Machine readable output",
        "dumpsys meminfo -s" to "Short summary",
        "dumpsys meminfo --oom" to "Group by oom score",
        "dumpsys window windows" to "Window list",
        "dumpsys window displays" to "Display info",
        "dumpsys window policy" to "Window policy state",
        "dumpsys window tokens" to "Window tokens",
        "dumpsys window visible-apps" to "Visible apps",
        "dumpsys battery set" to "Fake a battery value",
        "dumpsys battery unplug" to "Pretend the charger is unplugged",
        "dumpsys battery set level" to "Battery percentage",
        "dumpsys battery set status" to "Charging status code",
        "dumpsys battery set ac" to "AC charger connected, 0 or 1",
        "dumpsys battery set usb" to "USB charger connected, 0 or 1",
        "dumpsys battery set wireless" to "Wireless charger connected, 0 or 1",
        "dumpsys battery set present" to "Battery present, 0 or 1",
        "dumpsys battery set temp" to "Battery temperature in tenths of a degree",
        "dumpsys deviceidle enable" to "Turn Doze on",
        "dumpsys deviceidle disable" to "Turn Doze off",
        "dumpsys deviceidle step" to "Advance to the next Doze state",
        "dumpsys deviceidle force-idle" to "Force Doze now",
        "dumpsys deviceidle unforce" to "Leave forced Doze",
        "dumpsys deviceidle whitelist" to "Battery optimization exceptions",
        "dumpsys deviceidle get" to "Read a Doze value",
        "dumpsys batterystats --reset" to "Clear the collected stats",
        "dumpsys batterystats --checkin" to "Machine readable output",
        "dumpsys batterystats --charged" to "Since the last full charge",
        "dumpsys batterystats --history" to "Battery history log",
        "dumpsys procstats --hours" to "Last N hours",
        "dumpsys procstats --full-details" to "Everything",
        "dumpsys procstats --current" to "Current collection window",
        "svc nfc" to "Turn NFC on or off",
        "svc bluetooth" to "Turn Bluetooth on or off",
        "svc power reboot" to "Reboot, with an optional target",
        "svc power shutdown" to "Power the device off",
        "svc power stayon true" to "Stay on with any charger",
        "svc power stayon false" to "Normal screen timeout",
        "svc power stayon usb" to "Stay on over USB",
        "svc power stayon ac" to "Stay on with the AC charger",
        "svc power stayon wireless" to "Stay on with a wireless charger",
        "svc wifi enable" to "Turn Wi-Fi on",
        "svc wifi disable" to "Turn Wi-Fi off",
        "svc data enable" to "Turn mobile data on",
        "svc data disable" to "Turn mobile data off",
        "svc nfc enable" to "Turn NFC on",
        "svc nfc disable" to "Turn NFC off",
        "svc bluetooth enable" to "Turn Bluetooth on",
        "svc bluetooth disable" to "Turn Bluetooth off",
        "svc usb setFunctions" to "Set the USB mode",
        "svc usb getFunctions" to "Show the USB mode",
        "svc usb setScreenUnlockedFunctions" to "USB mode while unlocked",
        "wm folded-area" to "Simulate a folded area",
        "wm size reset" to "Back to the native resolution",
        "wm size -d" to "Target display id",
        "wm density reset" to "Back to the native DPI",
        "wm density -d" to "Target display id",
        "wm scaling off" to "No GPU scaling",
        "wm scaling auto" to "Automatic GPU scaling",
        "wm user-rotation free" to "Let rotation follow the sensor",
        "wm user-rotation lock" to "Lock the rotation",
        "wm user-rotation -d" to "Target display id",
        "input draganddrop" to "Drag from one point to another",
        "input press" to "Press the trackball",
        "input roll" to "Roll the trackball",
        "input motionevent" to "Send a raw motion event",
        "input keycombination" to "Press several keys together",
        "input keyevent --longpress" to "Long press the key",
        "ime list" to "List input methods",
        "ime enable" to "Enable an input method",
        "ime disable" to "Disable an input method",
        "ime set" to "Pick the active input method",
        "ime reset" to "Reset to the default input method",
        "ime list -a" to "All methods, enabled or not",
        "ime list -s" to "Only the ids",
        "ime enable --user" to "Target user id, 0 is the owner",
        "ime disable --user" to "Target user id, 0 is the owner",
        "ime set --user" to "Target user id, 0 is the owner",
        "appops list" to "List operations of a package",
        "appops start" to "Start an operation",
        "appops stop" to "Stop an operation",
        "appops query-op" to "Find packages by operation mode",
        "appops write-settings" to "Save app op settings now",
        "appops read-settings" to "Reload app op settings",
        "device_config list" to "List flags in a namespace",
        "device_config get" to "Read a flag",
        "device_config delete" to "Remove a flag",
        "device_config reset" to "Reset flags",
        "device_config set_sync_disabled_for_tests" to "Stop flag syncing for tests",
        "device_config get_sync_disabled_for_tests" to "Show the flag sync state",
        "logcat -s" to "Silence everything except these tags",
        "logcat -e" to "Only lines matching a regex",
        "logcat -m" to "Stop after this many lines",
        "logcat -f" to "Write to a file",
        "logcat -g" to "Show the ring buffer size",
        "logcat -T" to "Start this far back in the log",
        "logcat --pid" to "Only this process id",
        "logcat *:E" to "Errors only",
        "logcat *:W" to "Warnings and worse",
        "logcat *:I" to "Info and worse",
        "logcat *:S" to "Silence every tag",
        "logcat -b main" to "Main buffer",
        "logcat -b system" to "System buffer",
        "logcat -b crash" to "Crash buffer",
        "logcat -b events" to "Event buffer",
        "logcat -b radio" to "Radio buffer",
        "logcat -b all" to "Every buffer",
        "logcat -b default" to "Default buffers",
        "logcat -v brief" to "Priority, tag and pid",
        "logcat -v long" to "Every field on its own line",
        "logcat -v process" to "Process id only",
        "logcat -v raw" to "Message only",
        "logcat -v tag" to "Priority and tag only",
        "logcat -v thread" to "Process and thread ids",
        "logcat -v threadtime" to "Time, ids, priority and tag",
        "logcat -v time" to "Timestamped lines",
        "logcat -v color" to "Color by priority",
        "service check" to "Check whether a service exists",
        "service call" to "Call a binder transaction",
        "bmgr enabled" to "Show whether backup is on",
        "bmgr enable" to "Turn backup on or off",
        "bmgr restore" to "Restore a backup set",
        "bmgr list" to "List transports or backup sets",
        "bmgr transport" to "Pick the backup transport",
        "bmgr run" to "Run the backup pass now",
        "bmgr wipe" to "Erase the backup data of a package",
        "bmgr fullbackup" to "Full backup of a package",
        "bmgr backupnow --all" to "Back up every package",
        "bmgr list transports" to "Available backup transports",
        "bmgr list sets" to "Stored backup sets",
        "monkey -v" to "More verbose output",
        "monkey -s" to "Random seed",
        "monkey --throttle" to "Milliseconds between events",
        "monkey --pct-touch" to "Share of touch events",
        "monkey --pct-motion" to "Share of motion events",
        "monkey --ignore-crashes" to "Keep going after a crash",
        "monkey --ignore-timeouts" to "Keep going after an ANR",
        "content query" to "Read rows from a provider",
        "content insert" to "Insert a row",
        "content update" to "Update rows",
        "content delete" to "Delete rows",
        "content call" to "Call a provider method",
        "content read" to "Read a file from a provider",
        "content write" to "Write a file to a provider",
        "content query --uri" to "Content URI",
        "content query --user" to "Target user id, 0 is the owner",
        "content query --projection" to "Columns to return",
        "content query --where" to "Row filter",
        "content query --sort" to "Sort order",
        "content insert --uri" to "Content URI",
        "content insert --user" to "Target user id, 0 is the owner",
        "content insert --bind" to "Column and value to write",
        "content update --uri" to "Content URI",
        "content update --user" to "Target user id, 0 is the owner",
        "content update --bind" to "Column and value to write",
        "content update --where" to "Row filter",
        "content delete --uri" to "Content URI",
        "content delete --user" to "Target user id, 0 is the owner",
        "content delete --where" to "Row filter",
        "screencap -p" to "Write a PNG",
        "screencap -d" to "Display id",
        "screenrecord --size" to "Video resolution",
        "screenrecord --bit-rate" to "Bits per second",
        "screenrecord --time-limit" to "Seconds to record",
        "screenrecord --verbose" to "Show recording details",
        "screenrecord --bugreport" to "Overlay frame and timestamp info",
        "screenrecord --rotate" to "Rotate the video",
        "reboot recovery" to "Reboot into recovery",
        "reboot bootloader" to "Reboot into the bootloader",
        "reboot -p" to "Power off",
        "locksettings set-pin" to "Set a PIN",
        "locksettings set-password" to "Set a password",
        "locksettings set-pattern" to "Set a pattern",
        "locksettings clear" to "Remove the lock screen credential",
        "locksettings verify" to "Check the current credential",
        "locksettings get-disabled" to "Is the lock screen disabled",
        "locksettings set-disabled" to "Disable or enable the lock screen",
        "locksettings require-strong-auth" to "Force a strong auth prompt",
        "locksettings clear --old" to "The current credential",
        "locksettings set-pin --old" to "The current credential",
        "locksettings set-password --old" to "The current credential",
        "locksettings set-pattern --old" to "The current credential",
        "sm list-disks" to "Storage disks",
        "sm list-volumes" to "Storage volumes",
        "sm has-adoptable" to "Can storage be adopted",
        "sm get-primary-storage-uuid" to "Primary storage uuid",
        "dmesg -w" to "Follow new kernel messages",
        "dmesg -T" to "Human readable timestamps",
        "dmesg -c" to "Print and clear the buffer",
        "ls -l" to "Long listing",
        "ls -a" to "Include hidden files",
        "ls -la" to "Long listing with hidden files",
        "ls -lh" to "Long listing with readable sizes",
        "ls -R" to "Walk into subdirectories",
        "ls -t" to "Sort by time",
        "ls -S" to "Sort by size",
        "ls -d" to "The directory itself, not its contents",
        "ls -Z" to "Show SELinux labels",
        "ps -A" to "Every process",
        "ps -e" to "Every process",
        "ps -f" to "Full format",
        "ps -ef" to "Every process, full format",
        "ps -o" to "Pick the output columns",
        "ps -p" to "Only these pids",
        "ps -u" to "Only this user",
        "ps -T" to "Show threads",
        "top -n" to "Stop after this many refreshes",
        "top -m" to "Show this many processes",
        "top -d" to "Seconds between refreshes",
        "top -b" to "Batch output",
        "top -H" to "Show threads",
        "top -q" to "No delay between refreshes",
        "top -s" to "Sort by this column",
        "df -h" to "Readable sizes",
        "df -k" to "Sizes in kilobytes",
        "df -a" to "Include pseudo filesystems",
        "du -h" to "Readable sizes",
        "du -s" to "Total only",
        "du -sh" to "Readable total",
        "du -a" to "Include files",
        "du -d" to "How deep to go",
        "grep -i" to "Ignore case",
        "grep -v" to "Lines that do not match",
        "grep -r" to "Search directories",
        "grep -n" to "Show line numbers",
        "grep -E" to "Extended regex",
        "grep -c" to "Count matches",
        "grep -l" to "File names only",
        "grep -w" to "Whole words",
        "grep -o" to "Print the matching part",
        "grep -A" to "Lines after a match",
        "grep -B" to "Lines before a match",
        "find -name" to "Match the file name",
        "find -iname" to "Match the name, ignoring case",
        "find -type" to "f for file, d for directory",
        "find -maxdepth" to "How deep to go",
        "find -mindepth" to "Skip shallower levels",
        "find -size" to "Match by size",
        "find -mtime" to "Match by change time",
        "find -delete" to "Delete what matched",
        "find -exec" to "Run a command per match",
        "find -print" to "Print what matched",
        "rm -r" to "Delete directories too",
        "rm -f" to "Never ask, ignore missing files",
        "rm -rf" to "Delete a whole tree without asking",
        "rm -v" to "Say what is deleted",
        "rm -d" to "Remove an empty directory",
        "cp -r" to "Copy directories",
        "cp -f" to "Overwrite without asking",
        "cp -p" to "Keep timestamps and modes",
        "cp -a" to "Copy everything as it is",
        "cp -v" to "Say what is copied",
        "mv -f" to "Overwrite without asking",
        "mv -n" to "Never overwrite",
        "mv -v" to "Say what is moved",
        "mkdir -p" to "Create parent directories too",
        "mkdir -m" to "Set the mode",
        "chmod -R" to "Walk into subdirectories",
        "chmod 644" to "Owner writes, everyone reads",
        "chmod 755" to "Owner writes, everyone reads and runs",
        "chmod 777" to "Everyone reads, writes and runs",
        "chmod +x" to "Make it executable",
        "chmod -x" to "Remove the executable bit",
        "chown -R" to "Walk into subdirectories",
        "kill -9" to "Kill at once, SIGKILL",
        "kill -15" to "Ask to stop, SIGTERM",
        "kill -l" to "List signal names",
        "killall -9" to "Kill at once",
        "killall -l" to "List signal names",
        "killall -v" to "Say what is killed",
        "mount -o" to "Mount options",
        "mount -t" to "Filesystem type",
        "mount -r" to "Read only",
        "mount -w" to "Read and write",
        "mount remount" to "Remount an already mounted filesystem",
        "ping -c" to "How many packets",
        "ping -i" to "Seconds between packets",
        "ping -s" to "Packet size",
        "ping -w" to "Total timeout",
        "ping -W" to "Timeout per reply",
        "ip -4" to "IPv4 only",
        "ip -6" to "IPv6 only",
        "ip addr" to "Interface addresses",
        "ip route" to "Routing table",
        "ip link" to "Network interfaces",
        "ip rule" to "Routing rules",
        "ip neigh" to "ARP and neighbour table",
        "ip addr show" to "Show addresses",
        "ip addr add" to "Add an address",
        "ip addr del" to "Remove an address",
        "ip addr flush" to "Remove every address",
        "ip route show" to "Show routes",
        "ip route add" to "Add a route",
        "ip route del" to "Remove a route",
        "ip route get" to "Which route a target uses",
        "ip route flush" to "Remove every route",
        "ip link show" to "Show interfaces",
        "ip link set" to "Change an interface",
        "head -n" to "How many lines",
        "head -c" to "How many bytes",
        "tail -n" to "How many lines",
        "tail -c" to "How many bytes",
        "tail -f" to "Follow new lines",
        "wc -l" to "Count lines",
        "wc -w" to "Count words",
        "wc -c" to "Count bytes",
        "sort -r" to "Reverse order",
        "sort -n" to "Numeric order",
        "sort -u" to "Drop duplicates",
        "sort -k" to "Sort by a column",
        "sort -f" to "Ignore case",
        "uniq -c" to "Count repeats",
        "uniq -d" to "Only repeated lines",
        "uniq -u" to "Only unique lines",
        "uniq -i" to "Ignore case",
        "cut -d" to "Field separator",
        "cut -f" to "Which fields",
        "cut -c" to "Which characters",
        "sed -n" to "Print only what you ask for",
        "sed -e" to "Add a script",
        "sed -i" to "Edit the file in place",
        "sed -E" to "Extended regex",
        "tar -c" to "Create an archive",
        "tar -x" to "Extract",
        "tar -t" to "List contents",
        "tar -z" to "Gzip",
        "tar -v" to "Verbose",
        "tar -f" to "Archive file name",
        "tar -czf" to "Create a gzip archive",
        "tar -xzf" to "Extract a gzip archive",
        "unzip -l" to "List contents",
        "unzip -o" to "Overwrite without asking",
        "unzip -d" to "Where to extract",
        "unzip -q" to "Quiet",
        "xargs -n" to "Arguments per command",
        "xargs -I" to "Placeholder for each item",
        "xargs -0" to "Input split by null bytes",
        "stat -c" to "Custom output format",
        "stat -f" to "Filesystem info",
        "stat -L" to "Follow symlinks",
        "setenforce 0" to "SELinux permissive",
        "setenforce 1" to "SELinux enforcing",
        "setenforce Enforcing" to "SELinux enforcing",
        "setenforce Permissive" to "SELinux permissive",
        "date -u" to "UTC",
        "date -s" to "Set the time",
        "date +%Y-%m-%d" to "Print the date",
        "date +%H:%M:%S" to "Print the time",
        "date +%s" to "Unix timestamp",
        "free -h" to "Readable sizes",
        "free -m" to "Megabytes",
        "free -b" to "Bytes",
        "netstat -a" to "Every socket",
        "netstat -n" to "Numbers, no names",
        "netstat -t" to "TCP only",
        "netstat -u" to "UDP only",
        "netstat -l" to "Listening sockets",
        "netstat -p" to "Owning process",
        "getevent -l" to "Readable event names",
        "getevent -t" to "Timestamps",
        "getevent -p" to "Device properties",
        "getevent -i" to "Device details",

        "pm trim-caches 128M" to "Free space until 128 MB is free",
        "pm trim-caches 256M" to "Free space until 256 MB is free",
        "pm trim-caches 512M" to "Free space until 512 MB is free",
        "pm trim-caches 1G" to "Free space until 1 GB is free",
        "pm trim-caches 2G" to "Free space until 2 GB is free",
        "pm compile -m verify" to "Verify only, no optimization",
        "pm compile -m speed-profile" to "Optimize with the collected profile",
        "pm compile -m speed" to "Optimize everything for speed",
        "pm compile -m everything" to "Compile every method",
        "pm compile -r first-boot" to "As on the first boot",
        "pm compile -r boot-after-ota" to "As after a system update",
        "pm compile -r install" to "As right after installing",
        "pm compile -r bg-dexopt" to "As the background dexopt job",
        "pm compile -r cmdline" to "Manual run from the shell",
        "pm list packages --user 0" to "The owner user",
        "pm install --install-location 0" to "Auto",
        "pm install --install-location 1" to "Internal storage",
        "pm install --install-location 2" to "External storage",
        "am switch-user 0" to "The owner user",
        "am send-trim-memory HIDDEN" to "The app just went to the background",
        "am send-trim-memory RUNNING_MODERATE" to "Memory is getting tight",
        "am send-trim-memory BACKGROUND" to "The app is early in the background list",
        "am send-trim-memory RUNNING_LOW" to "Memory is low",
        "am send-trim-memory MODERATE" to "The app may be killed soon",
        "am send-trim-memory RUNNING_CRITICAL" to "Memory is critical",
        "am send-trim-memory COMPLETE" to "The app is first in line to be killed",
        "settings reset global untrusted_defaults" to "Reset app changes to their defaults",
        "settings reset global untrusted_clear" to "Remove settings written by apps",
        "settings reset global trusted_defaults" to "Reset everything to the defaults",
        "settings reset secure untrusted_defaults" to "Reset app changes to their defaults",
        "settings reset secure untrusted_clear" to "Remove settings written by apps",
        "settings reset secure trusted_defaults" to "Reset everything to the defaults",
        "settings put global stay_on_while_plugged_in 0" to "Never stay on",
        "settings put global stay_on_while_plugged_in 1" to "Stay on with the AC charger",
        "settings put global stay_on_while_plugged_in 2" to "Stay on over USB",
        "settings put global stay_on_while_plugged_in 3" to "Stay on with AC and USB",
        "settings put global stay_on_while_plugged_in 7" to "Stay on with any charger",
        "settings put system screen_brightness_mode 0" to "Manual brightness",
        "settings put system screen_brightness_mode 1" to "Automatic brightness",
        "settings put system screen_off_timeout 15000" to "15 seconds",
        "settings put system screen_off_timeout 30000" to "30 seconds",
        "settings put system screen_off_timeout 60000" to "1 minute",
        "settings put system screen_off_timeout 120000" to "2 minutes",
        "settings put system screen_off_timeout 600000" to "10 minutes",
        "settings put system screen_off_timeout 1800000" to "30 minutes",
        "settings put secure ui_night_mode 1" to "Light theme",
        "settings put secure ui_night_mode 2" to "Dark theme",
        "settings put secure navigation_mode 0" to "Three button navigation",
        "settings put secure navigation_mode 1" to "Two button navigation",
        "settings put secure navigation_mode 2" to "Gesture navigation",
        "device_config reset untrusted_defaults" to "Reset app changes to their defaults",
        "device_config reset untrusted_clear" to "Remove flags written by apps",
        "device_config reset trusted_defaults" to "Reset everything to the defaults",
        "svc power reboot recovery" to "Reboot into recovery",
        "svc power reboot bootloader" to "Reboot into the bootloader",
        "wm size 1080x2400" to "Full HD+ resolution",
        "wm size 1440x3200" to "Quad HD+ resolution",
        "wm size 720x1600" to "HD+ resolution",
        "wm density 320" to "xhdpi, smaller UI on phones",
        "wm density 420" to "Common phone density",
        "wm density 480" to "xxhdpi",
        "wm density 560" to "Between xxhdpi and xxxhdpi",
        "wm density 640" to "xxxhdpi, larger UI",
        "wm user-rotation lock 0" to "Portrait",
        "wm user-rotation lock 1" to "Landscape, rotated left",
        "wm user-rotation lock 2" to "Upside down portrait",
        "wm user-rotation lock 3" to "Landscape, rotated right",
        "setprop debug.hwui.renderer skiagl" to "Render with OpenGL",
        "setprop debug.hwui.renderer skiavk" to "Render with Vulkan",
        "setprop debug.hwui.overdraw show" to "Show the overdraw overlay",
        "setprop debug.hwui.overdraw false" to "Hide the overdraw overlay",
        "setprop persist.sys.usb.config mtp" to "USB file transfer",
        "setprop persist.sys.usb.config ptp" to "USB photo transfer",
        "setprop persist.sys.usb.config none" to "Charging only",
        "cat /proc/cpuinfo" to "CPU details",
        "cat /proc/meminfo" to "Memory details",
        "cat /proc/version" to "Kernel version",
        "cat /proc/uptime" to "Seconds since boot",
        "cat /proc/stat" to "Kernel and CPU counters",
        "cat /sys/class/power_supply/battery/capacity" to "Battery percentage",
        "cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq" to "Current clock of core 0",
        "sleep 1" to "Wait one second",
        "sleep 3" to "Wait three seconds",
        "sleep 5" to "Wait five seconds",
        "sleep 10" to "Wait ten seconds",
        "logcat -t 50" to "Last 50 lines",
        "logcat -t 100" to "Last 100 lines",
        "logcat -t 500" to "Last 500 lines",
        "logcat -t 1000" to "Last 1000 lines",
        "screenrecord --size 720x1280" to "HD video",
        "screenrecord --size 1080x1920" to "Full HD video",
        "screenrecord --time-limit 30" to "30 seconds",
        "screenrecord --time-limit 60" to "1 minute",
        "screenrecord --time-limit 120" to "2 minutes",
        "screenrecord --time-limit 180" to "3 minutes",
        "screenrecord --bit-rate 4000000" to "4 Mbps",
        "screenrecord --bit-rate 8000000" to "8 Mbps",
        "screenrecord --bit-rate 16000000" to "16 Mbps"
    )

    private fun runtimePermissions() = listOf(
        "android.permission.CAMERA",
        "android.permission.RECORD_AUDIO",
        "android.permission.ACCESS_FINE_LOCATION",
        "android.permission.ACCESS_COARSE_LOCATION",
        "android.permission.ACCESS_BACKGROUND_LOCATION",
        "android.permission.READ_CONTACTS",
        "android.permission.WRITE_CONTACTS",
        "android.permission.READ_CALENDAR",
        "android.permission.WRITE_CALENDAR",
        "android.permission.READ_PHONE_STATE",
        "android.permission.CALL_PHONE",
        "android.permission.READ_CALL_LOG",
        "android.permission.READ_SMS",
        "android.permission.SEND_SMS",
        "android.permission.RECEIVE_SMS",
        "android.permission.READ_EXTERNAL_STORAGE",
        "android.permission.WRITE_EXTERNAL_STORAGE",
        "android.permission.READ_MEDIA_IMAGES",
        "android.permission.READ_MEDIA_VIDEO",
        "android.permission.READ_MEDIA_AUDIO",
        "android.permission.POST_NOTIFICATIONS",
        "android.permission.BODY_SENSORS",
        "android.permission.ACTIVITY_RECOGNITION",
        "android.permission.BLUETOOTH_CONNECT",
        "android.permission.BLUETOOTH_SCAN",
        "android.permission.BLUETOOTH_ADVERTISE",
        "android.permission.NEARBY_WIFI_DEVICES",
        "android.permission.WRITE_SECURE_SETTINGS",
        "android.permission.DUMP",
        "android.permission.PACKAGE_USAGE_STATS"
    )

    private fun appOps() = listOf(
        "RUN_IN_BACKGROUND", "RUN_ANY_IN_BACKGROUND", "WAKE_LOCK", "SYSTEM_ALERT_WINDOW",
        "WRITE_SETTINGS", "GET_USAGE_STATS", "REQUEST_INSTALL_PACKAGES",
        "MANAGE_EXTERNAL_STORAGE", "START_FOREGROUND", "CAMERA", "RECORD_AUDIO",
        "COARSE_LOCATION", "FINE_LOCATION", "POST_NOTIFICATION", "SCHEDULE_EXACT_ALARM",
        "READ_CLIPBOARD", "WRITE_CLIPBOARD", "BOOT_COMPLETED", "INSTANT_APP_START_FOREGROUND"
    )

    private fun appOpModes() = listOf("allow", "deny", "ignore", "default")

    private fun deviceConfigNamespaces() = listOf(
        "activity_manager", "activity_manager_native_boot", "app_compat", "autofill",
        "connectivity", "content_capture", "device_idle", "game_driver", "input_native_boot",
        "media_native", "netd_native", "privacy", "runtime", "runtime_native",
        "runtime_native_boot", "storage_native_boot", "systemui", "telephony",
        "window_manager", "window_manager_native_boot"
    )

    private fun serviceNames() = listOf(
        "package", "activity", "window", "power", "battery", "statusbar", "notification",
        "phone", "SurfaceFlinger", "audio", "wifi", "connectivity", "clipboard",
        "input_method", "alarm", "media_session", "display", "sensorservice"
    )

    private fun keyEvents() = listOf(
        "KEYCODE_HOME", "KEYCODE_BACK", "KEYCODE_APP_SWITCH", "KEYCODE_POWER",
        "KEYCODE_WAKEUP", "KEYCODE_SLEEP", "KEYCODE_MENU", "KEYCODE_ENTER",
        "KEYCODE_DEL", "KEYCODE_TAB", "KEYCODE_SPACE", "KEYCODE_SEARCH",
        "KEYCODE_VOLUME_UP", "KEYCODE_VOLUME_DOWN", "KEYCODE_VOLUME_MUTE",
        "KEYCODE_BRIGHTNESS_UP", "KEYCODE_BRIGHTNESS_DOWN", "KEYCODE_CAMERA",
        "KEYCODE_MEDIA_PLAY_PAUSE", "KEYCODE_MEDIA_NEXT", "KEYCODE_MEDIA_PREVIOUS",
        "KEYCODE_MEDIA_STOP", "KEYCODE_DPAD_UP", "KEYCODE_DPAD_DOWN", "KEYCODE_DPAD_LEFT",
        "KEYCODE_DPAD_RIGHT", "KEYCODE_DPAD_CENTER", "KEYCODE_NOTIFICATION",
        "KEYCODE_SETTINGS", "KEYCODE_SCREENSHOT"
    )

    private fun intentActions() = listOf(
        "android.intent.action.VIEW",
        "android.intent.action.MAIN",
        "android.intent.action.SEND",
        "android.intent.action.DIAL",
        "android.intent.action.CALL",
        "android.intent.action.BOOT_COMPLETED",
        "android.intent.action.MEDIA_SCANNER_SCAN_FILE",
        "android.settings.SETTINGS",
        "android.settings.APPLICATION_DETAILS_SETTINGS",
        "android.settings.DEVELOPMENT_SETTINGS"
    )

    private fun globalKeys() = listOf(
        "window_animation_scale", "transition_animation_scale", "animator_duration_scale",
        "airplane_mode_on", "development_settings_enabled", "adb_enabled",
        "stay_on_while_plugged_in", "auto_time", "auto_time_zone", "device_name",
        "wifi_sleep_policy", "data_roaming", "low_power", "low_power_trigger_level",
        "heads_up_notifications_enabled", "wifi_scan_always_enabled",
        "ble_scan_always_enabled", "private_dns_mode", "private_dns_specifier"
    )

    private fun secureKeys() = listOf(
        "ui_night_mode", "screensaver_enabled", "location_mode", "default_input_method",
        "enabled_accessibility_services", "enabled_input_methods",
        "immersive_mode_confirmations", "sysui_qs_tiles", "navigation_mode",
        "doze_always_on", "one_handed_mode_enabled", "show_ime_with_hard_keyboard",
        "accessibility_display_daltonizer_enabled", "night_display_activated"
    )

    private fun systemKeys() = listOf(
        "screen_brightness", "screen_brightness_mode", "screen_off_timeout",
        "accelerometer_rotation", "haptic_feedback_enabled", "sound_effects_enabled",
        "peak_refresh_rate", "min_refresh_rate", "font_scale", "vibrate_when_ringing",
        "volume_music", "volume_ring", "volume_alarm", "pointer_speed", "show_touches"
    )

    private fun readableProps() = listOf(
        "ro.build.version.release", "ro.build.version.sdk", "ro.build.version.security_patch",
        "ro.build.fingerprint", "ro.product.model", "ro.product.brand", "ro.product.manufacturer",
        "ro.product.device", "ro.product.cpu.abi", "ro.serialno", "ro.boot.hardware",
        "ro.sf.lcd_density", "sys.boot_completed", "persist.sys.timezone",
        "persist.sys.locale", "debug.hwui.renderer", "gsm.operator.alpha",
        "ro.hardware", "ro.boot.bootloader", "dalvik.vm.heapsize"
    )

    private fun writableProps() = listOf(
        "debug.hwui.renderer", "debug.hwui.overdraw", "debug.layout",
        "persist.sys.timezone", "persist.sys.locale", "persist.sys.usb.config",
        "log.tag.stats_log", "debug.force_rtl"
    )

    private fun animationScales() = listOf("0", "0.25", "0.5", "0.75", "1", "1.5", "2")

    private fun boolInts() = listOf("0", "1")

    private val tokenDescriptions: Map<String, String> = mapOf(
        "android.permission.CAMERA" to "Camera access",
        "android.permission.RECORD_AUDIO" to "Microphone access",
        "android.permission.ACCESS_FINE_LOCATION" to "Precise location",
        "android.permission.ACCESS_COARSE_LOCATION" to "Approximate location",
        "android.permission.ACCESS_BACKGROUND_LOCATION" to "Location in the background",
        "android.permission.READ_CONTACTS" to "Read contacts",
        "android.permission.WRITE_CONTACTS" to "Change contacts",
        "android.permission.READ_CALENDAR" to "Read the calendar",
        "android.permission.WRITE_CALENDAR" to "Change the calendar",
        "android.permission.READ_PHONE_STATE" to "Phone and SIM state",
        "android.permission.CALL_PHONE" to "Place calls",
        "android.permission.READ_CALL_LOG" to "Read the call log",
        "android.permission.READ_SMS" to "Read SMS",
        "android.permission.SEND_SMS" to "Send SMS",
        "android.permission.RECEIVE_SMS" to "Receive SMS",
        "android.permission.READ_EXTERNAL_STORAGE" to "Read shared storage",
        "android.permission.WRITE_EXTERNAL_STORAGE" to "Write to shared storage",
        "android.permission.READ_MEDIA_IMAGES" to "Read photos",
        "android.permission.READ_MEDIA_VIDEO" to "Read videos",
        "android.permission.READ_MEDIA_AUDIO" to "Read audio files",
        "android.permission.POST_NOTIFICATIONS" to "Post notifications",
        "android.permission.BODY_SENSORS" to "Body sensors",
        "android.permission.ACTIVITY_RECOGNITION" to "Physical activity",
        "android.permission.BLUETOOTH_CONNECT" to "Connect to Bluetooth devices",
        "android.permission.BLUETOOTH_SCAN" to "Scan for Bluetooth devices",
        "android.permission.BLUETOOTH_ADVERTISE" to "Advertise over Bluetooth",
        "android.permission.NEARBY_WIFI_DEVICES" to "Nearby Wi-Fi devices",
        "android.permission.WRITE_SECURE_SETTINGS" to "Write secure settings",
        "android.permission.DUMP" to "Dump system service state",
        "android.permission.PACKAGE_USAGE_STATS" to "Read app usage stats",
        "RUN_IN_BACKGROUND" to "Run while in the background",
        "RUN_ANY_IN_BACKGROUND" to "Any background work",
        "WAKE_LOCK" to "Keep the CPU awake",
        "SYSTEM_ALERT_WINDOW" to "Draw over other apps",
        "WRITE_SETTINGS" to "Change system settings",
        "GET_USAGE_STATS" to "Read app usage stats",
        "REQUEST_INSTALL_PACKAGES" to "Install other apps",
        "MANAGE_EXTERNAL_STORAGE" to "Full storage access",
        "START_FOREGROUND" to "Start foreground services",
        "CAMERA" to "Camera access",
        "RECORD_AUDIO" to "Microphone access",
        "COARSE_LOCATION" to "Approximate location",
        "FINE_LOCATION" to "Precise location",
        "POST_NOTIFICATION" to "Post notifications",
        "SCHEDULE_EXACT_ALARM" to "Set exact alarms",
        "READ_CLIPBOARD" to "Read the clipboard",
        "WRITE_CLIPBOARD" to "Write to the clipboard",
        "BOOT_COMPLETED" to "Start at boot",
        "INSTANT_APP_START_FOREGROUND" to "Instant app foreground start",
        "allow" to "Allow the operation",
        "deny" to "Reject the operation",
        "ignore" to "Silently ignore the operation",
        "default" to "Use the platform default",
        "activity_manager" to "Activity manager flags",
        "activity_manager_native_boot" to "Activity manager flags read at boot",
        "app_compat" to "App compatibility flags",
        "autofill" to "Autofill flags",
        "connectivity" to "Connectivity subsystem",
        "content_capture" to "Content capture flags",
        "device_idle" to "Doze flags",
        "game_driver" to "Game driver flags",
        "input_native_boot" to "Input flags read at boot",
        "media_native" to "Native media flags",
        "netd_native" to "Network daemon flags",
        "privacy" to "Privacy flags",
        "runtime" to "ART runtime flags",
        "runtime_native" to "Native runtime flags",
        "runtime_native_boot" to "Native runtime flags read at boot",
        "storage_native_boot" to "Storage flags read at boot",
        "systemui" to "System UI flags",
        "telephony" to "Telephony flags",
        "window_manager" to "Window manager flags",
        "window_manager_native_boot" to "Window manager flags read at boot",
        "package" to "Package manager service",
        "activity" to "Activity manager service",
        "window" to "Window manager service",
        "power" to "Power service",
        "battery" to "Battery service",
        "statusbar" to "Status bar service",
        "notification" to "Notification service",
        "phone" to "Telephony service",
        "SurfaceFlinger" to "Display composition service",
        "audio" to "Audio service",
        "wifi" to "Wi-Fi service",
        "clipboard" to "Clipboard service",
        "input_method" to "Input method service",
        "alarm" to "Alarm service",
        "media_session" to "Media session service",
        "display" to "Display service",
        "sensorservice" to "Sensor service",
        "KEYCODE_HOME" to "Home key",
        "KEYCODE_BACK" to "Back key",
        "KEYCODE_APP_SWITCH" to "Recent apps key",
        "KEYCODE_POWER" to "Power key",
        "KEYCODE_WAKEUP" to "Wake the screen",
        "KEYCODE_SLEEP" to "Turn the screen off",
        "KEYCODE_MENU" to "Menu key",
        "KEYCODE_ENTER" to "Enter key",
        "KEYCODE_DEL" to "Backspace",
        "KEYCODE_TAB" to "Tab key",
        "KEYCODE_SPACE" to "Space key",
        "KEYCODE_SEARCH" to "Search key",
        "KEYCODE_VOLUME_UP" to "Volume up",
        "KEYCODE_VOLUME_DOWN" to "Volume down",
        "KEYCODE_VOLUME_MUTE" to "Mute",
        "KEYCODE_BRIGHTNESS_UP" to "Brightness up",
        "KEYCODE_BRIGHTNESS_DOWN" to "Brightness down",
        "KEYCODE_CAMERA" to "Camera key",
        "KEYCODE_MEDIA_PLAY_PAUSE" to "Play or pause",
        "KEYCODE_MEDIA_NEXT" to "Next track",
        "KEYCODE_MEDIA_PREVIOUS" to "Previous track",
        "KEYCODE_MEDIA_STOP" to "Stop playback",
        "KEYCODE_DPAD_UP" to "D-pad up",
        "KEYCODE_DPAD_DOWN" to "D-pad down",
        "KEYCODE_DPAD_LEFT" to "D-pad left",
        "KEYCODE_DPAD_RIGHT" to "D-pad right",
        "KEYCODE_DPAD_CENTER" to "D-pad select",
        "KEYCODE_NOTIFICATION" to "Open notifications",
        "KEYCODE_SETTINGS" to "Open settings",
        "KEYCODE_SCREENSHOT" to "Take a screenshot",
        "android.intent.action.VIEW" to "Open a URI",
        "android.intent.action.MAIN" to "Main entry point",
        "android.intent.action.SEND" to "Share content",
        "android.intent.action.DIAL" to "Open the dialer",
        "android.intent.action.CALL" to "Place a call",
        "android.intent.action.BOOT_COMPLETED" to "Boot finished broadcast",
        "android.intent.action.MEDIA_SCANNER_SCAN_FILE" to "Rescan a media file",
        "android.settings.SETTINGS" to "Open Settings",
        "android.settings.APPLICATION_DETAILS_SETTINGS" to "Open an app's info page",
        "android.settings.DEVELOPMENT_SETTINGS" to "Open developer options",
        "window_animation_scale" to "Window open and close animation speed",
        "transition_animation_scale" to "Activity transition animation speed",
        "animator_duration_scale" to "In-app animator speed",
        "airplane_mode_on" to "Airplane mode",
        "development_settings_enabled" to "Developer options",
        "adb_enabled" to "USB debugging",
        "stay_on_while_plugged_in" to "Keep the screen on while charging",
        "auto_time" to "Automatic date and time",
        "auto_time_zone" to "Automatic time zone",
        "device_name" to "Device name",
        "wifi_sleep_policy" to "Wi-Fi behaviour while asleep",
        "data_roaming" to "Data roaming",
        "low_power" to "Battery saver",
        "low_power_trigger_level" to "Battery saver trigger percentage",
        "heads_up_notifications_enabled" to "Pop-up notifications",
        "wifi_scan_always_enabled" to "Wi-Fi scanning while off",
        "ble_scan_always_enabled" to "Bluetooth scanning while off",
        "private_dns_mode" to "Private DNS mode",
        "private_dns_specifier" to "Private DNS host name",
        "ui_night_mode" to "Light or dark theme",
        "screensaver_enabled" to "Screen saver",
        "location_mode" to "Location mode",
        "default_input_method" to "Active keyboard",
        "enabled_accessibility_services" to "Enabled accessibility services",
        "enabled_input_methods" to "Enabled keyboards",
        "immersive_mode_confirmations" to "Immersive mode hint",
        "sysui_qs_tiles" to "Quick Settings tile order",
        "navigation_mode" to "Navigation style",
        "doze_always_on" to "Always-on display",
        "one_handed_mode_enabled" to "One handed mode",
        "show_ime_with_hard_keyboard" to "Keyboard with a hardware keyboard",
        "accessibility_display_daltonizer_enabled" to "Color correction",
        "night_display_activated" to "Night light",
        "screen_brightness" to "Brightness level",
        "screen_brightness_mode" to "Manual or automatic brightness",
        "screen_off_timeout" to "Screen timeout in milliseconds",
        "accelerometer_rotation" to "Auto rotate",
        "haptic_feedback_enabled" to "Touch vibration",
        "sound_effects_enabled" to "Touch sounds",
        "peak_refresh_rate" to "Highest refresh rate",
        "min_refresh_rate" to "Lowest refresh rate",
        "font_scale" to "Font size scale",
        "vibrate_when_ringing" to "Vibrate while ringing",
        "volume_music" to "Media volume",
        "volume_ring" to "Ring volume",
        "volume_alarm" to "Alarm volume",
        "pointer_speed" to "Pointer speed",
        "show_touches" to "Show touch marks",
        "ro.build.version.release" to "Android version",
        "ro.build.version.sdk" to "API level",
        "ro.build.version.security_patch" to "Security patch date",
        "ro.build.fingerprint" to "Build fingerprint",
        "ro.product.model" to "Model name",
        "ro.product.brand" to "Brand",
        "ro.product.manufacturer" to "Manufacturer",
        "ro.product.device" to "Device code name",
        "ro.product.cpu.abi" to "CPU architecture",
        "ro.serialno" to "Serial number",
        "ro.boot.hardware" to "Hardware platform",
        "ro.sf.lcd_density" to "Native screen density",
        "sys.boot_completed" to "Boot finished flag",
        "persist.sys.timezone" to "Time zone",
        "persist.sys.locale" to "System language",
        "debug.hwui.renderer" to "UI rendering backend",
        "gsm.operator.alpha" to "Mobile operator name",
        "ro.hardware" to "Hardware name",
        "ro.boot.bootloader" to "Bootloader version",
        "dalvik.vm.heapsize" to "Maximum app heap size",
        "debug.hwui.overdraw" to "Overdraw debug overlay",
        "debug.layout" to "Layout bounds overlay",
        "persist.sys.usb.config" to "USB mode",
        "log.tag.stats_log" to "Log level of the stats tag",
        "debug.force_rtl" to "Force right-to-left layout"
    )

    private val animationScaleDescriptions: Map<String, String> = mapOf(
        "0" to "Animations off",
        "0.25" to "Quarter of the normal duration",
        "0.5" to "Half the normal duration",
        "0.75" to "Slightly faster than normal",
        "1" to "Normal duration",
        "1.5" to "Half again as long",
        "2" to "Twice as long"
    )

    private val boolIntDescriptions: Map<String, String> = mapOf(
        "0" to "Off",
        "1" to "On"
    )

    private val descriptions: Map<String, String> = buildMap {
        putAll(baseDescriptions)
        args.forEach { (path, pools) ->
            pools.forEach { pool ->
                val table = when (pool) {
                    animationScales() -> animationScaleDescriptions
                    boolInts() -> boolIntDescriptions
                    else -> tokenDescriptions
                }
                pool.forEach { token ->
                    table[token]?.let { putIfAbsent("$path $token", it) }
                }
            }
        }
    }

    fun suggest(
        text: String,
        cursor: Int,
        installedPackages: List<String> = emptyList()
    ): List<Suggestion> {
        val safeCursor = cursor.coerceIn(0, text.length)
        val statement = text.substring(0, safeCursor).let { prefix ->
            val cut = prefix.lastIndexOfAny(separators)
            if (cut >= 0) prefix.substring(cut + 1) else prefix
        }

        val endsWithSpace = statement.isNotEmpty() && statement.last().isWhitespace()
        val tokens = statement.trim().split(Regex("\\s+")).filter { it.isNotEmpty() }
        val partial = if (endsWithSpace) "" else tokens.lastOrNull().orEmpty()
        val preceding = if (endsWithSpace) tokens else tokens.dropLast(1)

        val resolved = if (preceding.isEmpty()) {
            Resolved(topLevel, "")
        } else {
            resolve(preceding) ?: return emptyList()
        }

        val pool = resolved.pool.flatMap { token ->
            if (token == PACKAGES) installedPackages else listOf(token)
        }

        val ordered = if (partial.isEmpty()) {
            pool
        } else {
            val prefixed = pool.filter {
                it.startsWith(partial, ignoreCase = true) && !it.equals(partial, ignoreCase = true)
            }
            val contained = pool.filter {
                !it.startsWith(partial, ignoreCase = true) && it.contains(partial, ignoreCase = true)
            }
            val exact = pool.filter { it.equals(partial, ignoreCase = true) }
            prefixed + contained + exact
        }

        return ordered.distinct().map { token ->
            Suggestion(token = token, description = describe(resolved.path, token))
        }
    }

    private class Resolved(val pool: List<String>, val path: String)

    private fun resolve(precedingRaw: List<String>): Resolved? {
        val preceding = applyAlias(precedingRaw)

        for (size in preceding.size downTo 1) {
            val path = preceding.take(size)
            val key = path.joinToString(" ")
            val opts = options[key]
            val argPools = args[key]
            if (opts == null && argPools == null) continue

            val rest = preceding.drop(size)
            var consumed = 0
            var index = 0
            while (index < rest.size) {
                val token = rest[index]
                if (token.startsWith("-")) {
                    if (takesValue(key, token)) {
                        if (index == rest.size - 1) {
                            val values = args["$key $token"]?.firstOrNull().orEmpty()
                            return if (values.isEmpty()) null else Resolved(values, "$key $token")
                        }
                        index++
                    }
                } else {
                    consumed++
                }
                index++
            }

            val pool = if (consumed == 0) {
                opts.orEmpty() + argPools?.firstOrNull().orEmpty()
            } else {
                argPools?.getOrNull(consumed).orEmpty()
            }
            return if (pool.isEmpty()) null else Resolved(pool, key)
        }
        return null
    }

    private val valueFlags = setOf(
        "--user", "--install-location", "--versionCode", "--namespace", "--uri",
        "--where", "--sort", "--bind", "--projection", "--old", "--throttle",
        "--pct-touch", "--pct-motion", "--time-limit", "--bit-rate", "--size",
        "--rotate", "--pid", "--hours", "--split"
    )

    private fun takesValue(path: String, flag: String): Boolean =
        flag in valueFlags || args.containsKey("$path $flag")

    private fun applyAlias(preceding: List<String>): List<String> {
        aliases.forEach { (from, to) ->
            if (preceding.size >= from.size && preceding.take(from.size) == from) {
                return to + preceding.drop(from.size)
            }
        }
        return preceding
    }

    private fun describe(path: String, token: String): String {
        val key = if (path.isEmpty()) token else "$path $token"
        return descriptions[key].orEmpty()
    }

    fun apply(text: String, cursor: Int, suggestion: String): Pair<String, Int> {
        val safeCursor = cursor.coerceIn(0, text.length)
        val prefix = text.substring(0, safeCursor)
        val start = prefix.indexOfLast { it.isWhitespace() } + 1
        var end = safeCursor
        while (end < text.length && !text[end].isWhitespace()) end++
        val replaced = prefix.substring(0, start) + suggestion + " "
        return (replaced + text.substring(end)) to replaced.length
    }
}
